services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  clamav:
    image: clamav/clamav:stable
    ports:
      - "3310:3310"
    volumes:
      - clamav-data:/var/lib/clamav

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis
      - clamav

  worker:
    build: .
    command: celery -A config worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
      - clamav

  beat:
    build: .
    command: celery -A config beat --loglevel=info
    env_file: .env
    depends_on:
      - redis

volumes:
  clamav-data:
