# Generated by Django 6.1 on 2026-08-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fileupload',
            new_name='upload_file_key_a707e3_idx',
            old_name='upload_file_key_idx',
        ),
        migrations.RenameIndex(
            model_name='fileupload',
            new_name='upload_file_status_da841a_idx',
            old_name='upload_file_status_idx',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='user',
        ),
    ]
